# Double Tap Left: Toggle Power Mode
MBTN_LEFT_DBL script-message toggle-power-mode

# Double Tap Right: Smart Action (Skip Intro IF Active, ELSE Toggle Audio)
MBTN_RIGHT_DBL script-message smart-skip-audio